# Generated by Django 3.2.5 on 2021-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(editable=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
